name: Release
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy-databricks-workflow:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.x"
      - name: Install Hatch
        run: pip install hatch
      - name: Install build
        run: pip install build
      - name: build python wheel package
        run: python -m build
      # - name: Get wheel file name
      #   id: get-wheel-file-name
      #   working-directory: ./dist
      #   run: echo "wheel=$(ls -1t *.whl | head -n1)" >> $GITHUB_OUTPUT
      # - name: Create Release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     VERSION=`hatch version`
      #     gh release create $VERSION --target main --generate-notes
