name: Test

on:
  push:
    branches:
      - main
  workflow_call:

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  linter:
    uses: ./.github/workflows/linter.yml

  run:
    name: Test
    runs-on: ubuntu-latest
    needs: linter
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.x"
      - name: Ensure latest pip
        run: python -m pip install --upgrade pip
      - name: Install Hatch
        run: pip install hatch
      - name: Run tests
        run: hatch run cov
